# version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
      - ./docker/ollama/init.sh:/init.sh
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    entrypoint: ["/init.sh"]
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto-app
    # restart: unless-stopped
    depends_on:
      - mongodb
      - ollama
      - minio
    volumes:
      - ./src:/app/src
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    command: ["uv", "run", "python", "-m", "src.main"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
